/**
 * @module optimizer
 *
 * Launches SkillOpt as a child process and manages the optimization job
 * lifecycle: job preparation, process execution, progress streaming,
 * timeout enforcement, and retry logic.
 */

import { spawn } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join, resolve } from "node:path";
import { randomUUID } from "node:crypto";

import type {
  SkillOptAdapterConfig,
  OptimizationJob,
  SkillOptProgressEvent,
  AdapterEventListener,
  TrajectoryRecord,
} from "./types.js";
import { TrajectoryRecorder } from "./trajectory.js";

export class OptimizerError extends Error {
  constructor(
    message: string,
    public readonly jobId: string,
    public readonly cause?: unknown,
  ) {
    super(`[skillopt-adapter/optimizer] Job ${jobId}: ${message}`);
    this.name = "OptimizerError";
  }
}

// ─── SkillOpt Version Check ───────────────────────────────────────────────────

/**
 * Verify that the installed SkillOpt version satisfies the configured
 * constraint. Returns the installed version string.
 *
 * @throws OptimizerError if SkillOpt is not installed or version mismatch
 */
export async function checkSkillOptInstalled(
  python: string,
  versionConstraint: string,
): Promise<string> {
  return new Promise((resolve_, reject) => {
    const proc = spawn(python, ["-m", "skillopt", "--version"], {
      stdio: ["ignore", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";
    proc.stdout?.on("data", (chunk: Buffer) => {
      stdout += chunk.toString();
    });
    proc.stderr?.on("data", (chunk: Buffer) => {
      stderr += chunk.toString();
    });

    proc.on("close", (code) => {
      if (code !== 0) {
        reject(
          new OptimizerError(
            `SkillOpt not found or failed to start. ` +
              `Run: pip install "skillopt${versionConstraint}"\n` +
              `stderr: ${stderr}`,
            "version-check",
          ),
        );
        return;
      }

      // Extract version from output like "skillopt 0.2.0"
      const match = stdout.trim().match(/(\d+\.\d+\.\d+)/);
      const version = match?.[1] ?? stdout.trim();
      resolve_(version);
    });

    proc.on("error", (err) => {
      reject(
        new OptimizerError(
          `Failed to spawn Python: ${err.message}`,
          "version-check",
          err,
        ),
      );
    });
  });
}

// ─── Job Builder ─────────────────────────────────────────────────────────────

/** Paths needed for an optimization job. */
export interface JobPaths {
  readonly jobDir: string;
  readonly skillOptConfigPath: string;
  readonly trajectoryExportPath: string;
  readonly candidateOutputPath: string;
}

/**
 * Prepare the filesystem layout for an optimization job:
 * - Create job directory in candidates dir
 * - Write SkillOpt run config YAML
 * - Export trajectories in SkillOpt format
 *
 * Returns the job paths.
 */
export function prepareJob(
  job: OptimizationJob,
  config: SkillOptAdapterConfig,
  trajectories: TrajectoryRecord[],
  recorder: TrajectoryRecorder,
): JobPaths {
  const jobDir = join(config.candidates.storageDir, job.id);
  mkdirSync(jobDir, { recursive: true });

  const trajectoryExportPath = join(jobDir, "trajectories.ndjson");
  const candidateOutputPath = join(jobDir, "candidate");
  const skillOptConfigPath = join(jobDir, "skillopt-run.yaml");

  mkdirSync(join(jobDir, "candidate"), { recursive: true });

  // Export trajectories in SkillOpt format
  recorder.exportForSkillOpt(
    trajectories,
    trajectoryExportPath,
  );

  // Write SkillOpt run config (YAML, compatible with SkillOpt's configs/ format)
  const runConfig = buildSkillOptRunConfig(
    job,
    config,
    trajectoryExportPath,
    candidateOutputPath,
  );
  writeFileSync(skillOptConfigPath, runConfig, "utf8");

  return {
    jobDir,
    skillOptConfigPath,
    trajectoryExportPath,
    candidateOutputPath,
  };
}

/**
 * Build the YAML configuration that SkillOpt will use for this run.
 * Maps AGY adapter config to SkillOpt's expected YAML format.
 */
function buildSkillOptRunConfig(
  job: OptimizationJob,
  config: SkillOptAdapterConfig,
  trajectoryPath: string,
  outputPath: string,
): string {
  const optConf = config.optimizer;

  return `# Auto-generated by skillopt-adapter for job ${job.id}
# Do not edit manually.

model:
  backend: ${optConf.backend}
  optimizer: ${optConf.model}
  target: ${optConf.model}

train:
  num_epochs: ${optConf.epochs}
  batch_size: ${optConf.batchSize}

env:
  name: "agy"
  skill_init: ${job.skillPath}
  data_path: ${trajectoryPath}
  out_root: ${outputPath}
`;
}

// ─── SkillOpt Process ─────────────────────────────────────────────────────────

/**
 * Run SkillOpt as a child process for the given job.
 *
 * Streams NDJSON progress events to the provided listener.
 * Enforces the configured timeout.
 * Returns the path to the produced candidate SKILL.md, or throws on failure.
 *
 * @throws OptimizerError on process failure, timeout, or no output
 */
export async function runSkillOptProcess(
  job: OptimizationJob,
  paths: JobPaths,
  config: SkillOptAdapterConfig,
  onEvent: AdapterEventListener,
): Promise<string> {
  const { python, version: _version } = config.skillopt;
  const { timeoutMs, retryAttempts, retryDelayMs } = config.optimizer;

  let lastError: unknown;
  for (let attempt = 0; attempt < retryAttempts; attempt++) {
    if (attempt > 0) {
      await delay(retryDelayMs);
    }
    try {
      return await runOnce(job, paths, python, timeoutMs, onEvent);
    } catch (err) {
      lastError = err;
      // Only retry on transient errors, not on optimization-failure exits
      if (err instanceof OptimizerError && err.message.includes("exit 2")) {
        throw err; // validation failure — don't retry
      }
      console.warn(
        `[skillopt-adapter/optimizer] Attempt ${attempt + 1}/${retryAttempts} ` +
          `failed for job ${job.id}: ${String(err)}`,
      );
    }
  }
  throw new OptimizerError(
    `All ${retryAttempts} attempts failed: ${String(lastError)}`,
    job.id,
    lastError,
  );
}

function runOnce(
  job: OptimizationJob,
  paths: JobPaths,
  python: string,
  timeoutMs: number,
  onEvent: AdapterEventListener,
): Promise<string> {
  return new Promise((resolve_, reject) => {
    // Upstream SkillOpt uses `skillopt-train` script.
    // We invoke it via python module to ensure it runs in the configured python env.
    const args = [
      "-m",
      "scripts.train",
      "--config",
      paths.skillOptConfigPath,
    ];

    const proc = spawn(python, args, {
      stdio: ["ignore", "pipe", "pipe"],
      env: {
        ...process.env,
        PYTHONUNBUFFERED: "1",
      },
    });

    let stdoutBuffer = "";
    let stderrBuffer = "";
    let settled = false;

    const timeoutHandle = setTimeout(() => {
      if (!settled) {
        settled = true;
        proc.kill("SIGTERM");
        reject(
          new OptimizerError(
            `Process timed out after ${timeoutMs}ms`,
            job.id,
          ),
        );
      }
    }, timeoutMs);

    proc.stdout?.on("data", (chunk: Buffer) => {
      stdoutBuffer += chunk.toString();
      const lines = stdoutBuffer.split("\n");
      // All complete lines are in indices 0..n-2; the last may be incomplete
      stdoutBuffer = lines.pop() ?? "";

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) continue;
        try {
          const event = JSON.parse(trimmed) as SkillOptProgressEvent;
          handleProgressEvent(event, job, onEvent);
        } catch {
          // Non-JSON output — log and continue
          console.debug(
            `[skillopt-adapter/optimizer] Non-JSON stdout: ${trimmed}`,
          );
        }
      }
    });

    proc.stderr?.on("data", (chunk: Buffer) => {
      stderrBuffer += chunk.toString();
    });

    proc.on("close", (code) => {
      clearTimeout(timeoutHandle);
      if (settled) return;
      settled = true;

      if (code === 0) {
        const candidatePath = join(paths.candidateOutputPath, "best_skill.md");
        if (!existsSync(candidatePath)) {
          reject(
            new OptimizerError(
              `SkillOpt exited 0 but candidate not found at ${candidatePath}`,
              job.id,
            ),
          );
          return;
        }
        resolve_(candidatePath);
      } else if (code === 2) {
        reject(
          new OptimizerError(
            `exit 2: SkillOpt produced no improvement over baseline`,
            job.id,
          ),
        );
      } else {
        reject(
          new OptimizerError(
            `Process exited with code ${code}. stderr: ${stderrBuffer.slice(0, 2000)}`,
            job.id,
          ),
        );
      }
    });

    proc.on("error", (err) => {
      clearTimeout(timeoutHandle);
      if (!settled) {
        settled = true;
        reject(
          new OptimizerError(
            `Failed to spawn SkillOpt: ${err.message}`,
            job.id,
            err,
          ),
        );
      }
    });
  });
}

function handleProgressEvent(
  event: SkillOptProgressEvent,
  job: OptimizationJob,
  onEvent: AdapterEventListener,
): void {
  switch (event.event) {
    case "epoch_start":
    case "update":
    case "skip":
      onEvent({
        type: "optimization:progress",
        timestamp: new Date().toISOString(),
        skillName: job.skillName,
        jobId: job.id,
        epoch: event.epoch ?? 0,
        totalEpochs: 0, // populated later from config
        message: event.message ?? `${event.event}`,
      });
      break;
    case "error":
      console.error(
        `[skillopt-adapter/optimizer] SkillOpt error event: ${event.error}`,
      );
      break;
    default:
      break;
  }
}

// ─── Job Queue ────────────────────────────────────────────────────────────────

/**
 * OptimizationScheduler manages the async job queue.
 * Jobs are enqueued synchronously and drained asynchronously.
 */
export class OptimizationScheduler {
  private readonly queue: OptimizationJob[] = [];
  private readonly config: SkillOptAdapterConfig;
  private readonly recorder: TrajectoryRecorder;
  private readonly eventListeners: AdapterEventListener[] = [];
  private draining = false;

  constructor(
    config: SkillOptAdapterConfig,
    recorder: TrajectoryRecorder,
  ) {
    this.config = config;
    this.recorder = recorder;
  }

  /** Register an event listener. */
  on(listener: AdapterEventListener): void {
    this.eventListeners.push(listener);
  }

  /** Remove an event listener. */
  off(listener: AdapterEventListener): void {
    const idx = this.eventListeners.indexOf(listener);
    if (idx !== -1) this.eventListeners.splice(idx, 1);
  }

  /** Enqueue an optimization job (synchronous, non-blocking). */
  enqueue(skillName: string, skillPath: string): string {
    const jobId = randomUUID();
    const job: OptimizationJob = {
      id: jobId,
      skillName,
      skillPath: resolve(skillPath),
      trajectoryPaths: [],
      configPath: "",
      outputDir: join(this.config.candidates.storageDir, jobId),
      enqueuedAt: new Date().toISOString(),
      status: "queued",
      startedAt: null,
      completedAt: null,
      candidateId: null,
      failureReason: null,
    };
    this.queue.push(job);

    // Start draining asynchronously without blocking the caller
    if (!this.draining) {
      setImmediate(() => void this.drain());
    }

    return jobId;
  }

  /** Get current queue length. */
  get queueLength(): number {
    return this.queue.length;
  }

  // ── Private ────────────────────────────────────────────────────────────────

  private async drain(): Promise<void> {
    if (this.draining) return;
    this.draining = true;

    const { parallelism } = this.config.optimizer;
    const running: Promise<void>[] = [];

    while (this.queue.length > 0 || running.length > 0) {
      // Fill up to parallelism
      while (this.queue.length > 0 && running.length < parallelism) {
        const job = this.queue.shift()!;
        const p = this.runJob(job).catch((err) => {
          console.error(
            `[skillopt-adapter/scheduler] Unhandled job error: ${String(err)}`,
          );
        });
        running.push(p);
      }

      if (running.length > 0) {
        // Wait for at least one to finish
        await Promise.race(running);
        // Remove completed promises
        for (let i = running.length - 1; i >= 0; i--) {
          let settled = false;
          void running[i]!.then(() => { settled = true; }).catch(() => { settled = true; });
          // Micro-task flush
          await Promise.resolve();
          if (settled) running.splice(i, 1);
        }
      }
    }

    this.draining = false;
  }

  private async runJob(job: OptimizationJob): Promise<void> {
    const skillName = job.skillName;
    job.status = "running";
    job.startedAt = new Date().toISOString();

    this.emit({
      type: "optimization:started",
      timestamp: new Date().toISOString(),
      skillName,
      jobId: job.id,
      trajectoryCount: 0,
    });

    try {
      const trajectories = this.recorder.loadTrajectories(skillName);
      const paths = prepareJob(job, this.config, trajectories, this.recorder);

      const candidatePath = await runSkillOptProcess(
        job,
        paths,
        this.config,
        this.emit.bind(this),
      );

      const candidateId = `${skillName}-${job.id}`;
      job.candidateId = candidateId;
      job.status = "completed";
      job.completedAt = new Date().toISOString();

      this.emit({
        type: "optimization:completed",
        timestamp: new Date().toISOString(),
        skillName,
        jobId: job.id,
        candidateId,
      });

      void candidatePath; // used by evaluator downstream
    } catch (err) {
      job.status = "failed";
      job.failureReason = String(err);
      job.completedAt = new Date().toISOString();

      this.emit({
        type: "optimization:failed",
        timestamp: new Date().toISOString(),
        skillName,
        jobId: job.id,
        reason: String(err),
      });
    }
  }

  private emit(
    event: Parameters<AdapterEventListener>[0],
  ): void {
    for (const listener of this.eventListeners) {
      try {
        listener(event);
      } catch (err) {
        console.error(
          `[skillopt-adapter/scheduler] Event listener error: ${String(err)}`,
        );
      }
    }
  }
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function delay(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

// Re-export for use in CLI
export { readFileSync };
